name: sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Once a day

permissions:
  contents: write

jobs:
  update-sponsors:
    name: Update sponsors
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Fetch sponsors
        run: pnpm tsx ./scripts/fetch-sponsors.ts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit
        run: |
          if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name 'Hiroki Osame'
          git config user.email 'hiroki.osame@gmail.com'
          git commit -am 'chore: update sponsors'
          git push
